<!-- PAGE D'ACCUEIL-->
<div id="onglet1" class="tab tab-active">


    <div id="intro" class="row">

        <!-- PAGE D'ACCUEIL
<div id="welcome-img-paragraph" class="col-xl-6 col-lg-4 col-md-8 col-sm-10"></div>-->
        <div id="bienvenue" class="col-xl-6 col-lg-5 col-md-12 col-sm-12">
            <h3 class="lobster-two"> Bienvenue Chez Mellie votre Salon de Thé de Mauriac</h3>
            <p>« Chez Mellie» c'est un Salon de Thé, simple et chaleureux avec ses cookies et financiers faits maison (par Mellie elle-même!), un espace de douceur pour se marrer, profiter, se détendre en solo, entre amis ou en famille. </p>
        </div>




        <div id="home-schedule-area" class="col-xl-6 col-lg-4 col-md-8 col-sm-10">
            <div id="home-schedule-box">
                <div id="home-schedule-box-inner">
                    <h3 class="lobster-two">Horaires du magasin</h3>
                    <table>
                        <tbody>
                            <tr>
                                <td>Semaine: </td>
                                <td> 8H - 18H</td>
                            </tr>

                            <tr>
                                <td>Samedi: </td>
                                <td></td>
                            </tr>

                            <tr>
                                <td>Dimanche: </td>
                                <td> FERME</td>
                            </tr>

                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>




    <div id="menu">
        <div class="row flex" id="img-salon">
            <div class="losange">
                <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12" id="text-menu">
                    <h3 class="lobster-two">Vous voulez Manger à Mauriac ?</h3>

                    <span class="maketable">
                        <span class="border-line"> </span>
                        <span class="icon-between-line"> <img src="https://img.icons8.com/dusk/64/000000/paella.png" />
                        </span>
                        <span class="border-line"> </span>
                    </span>
                    <p>Les midis, Chez Mellie vous propose sa formule du jour, toujours fait maison, avec les produits de nos partenaires producteurs. Chez Mellie, on sort du traditionnel « aligot saucisse » et on aime manger local en variant les saveurs !
                        Chez Mellie s'adapte à vos envies :
                        <ul>
                            <li> Formule sur place dans une ambiance chaleureuse</li>

                            <li> Vente à emporter pour savourer votre repas et profiter des paysages du Cantal</li>

                            <li> Restaurant adapté aux enfants avec une formule spéciale et un coin jeux.</li>

                            <li> Mangez végétarien dans le Cantal ? C'est possible Chez Mellie, j'adapte la formule pour vous quand je suis prévenue.</li>
                            <li>Repartez avec des gourmandises des artisans du Cantal et de la Corrèze : cookies, sirops, confitures, ...</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>

    </div>
</div>


<aside id="engagement">
    <div id="engagement-text" class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
        <h3 class="lobster-two">Nos engagements </h3>

        <div class="textwidget">
            <p>Soutenir les producteurs du territoire cantalien</p>
            <p>Des prix justes du producteur au consommateur</p>
            <p>Un lieu convivial de conseil et de partage</p>
        </div>
    </div>
</aside>


<aside id="home-newsletter">
    <section id="home-newsletter-inner" class="col-xl-4 col-lg-5 col-md-8 col-sm-12">
        <h4 class="lobster-two">Newsletter</h4>
        <div>
            <p>Recevez les animations et les infos du Salon en cliquant sur l'icône</p>
            <a href="https://gmail.us10.list-manage.com/subscribe?u=11bd8e48ef4710863cde5ef5e&id=1e0ae2d2cc" target="_blank"> <img src="https://img.icons8.com/clouds/100/000000/mailbox-plane.png" />
            </a>
        </div>

    </section>
</aside>

</div>
<!--FIN PAGE D'ACCUEIL -->