<div id="news-pills">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">NEWS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">INSTAGRAM</a>
        </li>
    </ul>
</div>

<div class="tab-content" id="pills-tabContent">

    <!-- ONGLET ARTICLES -->
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

        <div class="row">
            <div class="filters col-xl-2 col-lg-3 col-md-3 col-sm-12">
               
                <div class="ui-group">
                    <div class="button-group js-radio-button-group nav-news" data-filter-group="category" id="news-category-list">
                        <h3 id="category-title">Catégories</h3>
                        <button class="button is-checked nav-news" data-filter=""> Tous </button>
                        <?php foreach ($categories as $categorie) : ?>
                            <button class="button nav-news" data-filter=".<?= strtolower($categorie['name']); ?>"> <?= htmlspecialchars($categorie['name']); ?></button>
                        <?php endforeach; ?>
                    </div>
                </div>

            </div>

            <div class="grid col-xl-10 col-lg-9 col-md-9 col-sm-12">
                <?php foreach ($news as $new) : ?>

                    <!-- Pour chaque article... -->
                    <div class="category grid-item  <?= strtolower($new['name']); ?> ">
                        <img src="img/news/<?= htmlspecialchars($new['image']); ?>" alt="<?= htmlspecialchars($new['title']); ?>">
                        <div class="description">
                            <h1 class="lobster-two"><?= htmlspecialchars($new['title']); ?></h1>
                            <div><?= htmlspecialchars(mb_substr($new['content'], 0, 500, 'UTF-8')); ?></div>
                            <p class="read-more">
                                <time datetime="<?= htmlspecialchars($new['createdAt']); ?>"><?= date('d/m/Y', strtotime(htmlspecialchars($new['createdAt']))); ?></time>
                                <div>
                                    <p>#<?= htmlspecialchars(mb_substr($new['name'], 0, 500, 'UTF-8')); ?></p>
                                </div>
                            </p>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

        </div>
    </div>
    <!-- ONGLET INSTAGRAM-->
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <script src="https://apps.elfsight.com/p/platform.js" defer></script>
        <div class="elfsight-app-e567933b-f5be-47be-b842-4d3063290be8"></div>
    </div>

</div>




<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

<script src="js/tea-selection.js"></script>
<!--
 <script src="js/nav.js"> </script>
                 -->

<script src="js/news.js"></script>