<!doctype html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?php echo $view; ?></title>

    <link rel="stylesheet" href="css/style.css" type="text/css">
    <link rel="stylesheet" href="css/<?php echo  $view . ".css"; ?>" type="text/css">
    <link rel="stylesheet" href="css/<?php echo  $view . ".css"; ?>" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Londrina+Solid:wght@300&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Yellowtail&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fredericka+the+Great&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rye&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bentham|Playfair+Display|Raleway:400,500|Suranna|Trocchi" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Old+Standard+TT&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Itim&family=Parisienne&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mate+SC&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:ital,wght@1,300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Grandstander:wght@100&display=swap" rel="stylesheet">
    <!--CHARGEMENT JQUERY-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>


<body>

    <?php if ($view !== "login" && $view !== "admin/admin" && $view !== "admin/add_tea") : ?>


        <div class="parallax" id="top-img">
            <h1 class="yellow-tail big-tittle">Chez Mellie</h1>
            <img src="img/mellie.png" id="home-top-salon-icon">
            <h1 class="yellow-tail big-tittle">Salon de thé</h1>

        </div>

        <div class="background-white no-margin">

            <nav class="container" id="nav-bar-central">
                <ul class="tab-nav no-margin">

                    <li><a href="<?= buildUrl('/'); ?>" class="tab-nav-active">Chez Mellie</a></li>
                    <li><a href="<?= buildUrl('/actu'); ?>">Actu</a></li>
                    <li><a href="<?= buildUrl('/the'); ?>">Thé-infusion</a></li>
                    <li> <a href="<?= buildUrl('/jeu'); ?>">GRENIER AUX TROLLS</a> </li>
                    <li> <a href="<?= buildUrl('/contact'); ?>">Contact</a> </li>

                </ul>

            </nav>
        </div>
    <?php endif ?>

    <main>
        <?php include VIEWS_DIR . '/' . $view . '.phtml'; ?>
    </main>




    <!-- FOOTER -->

    <?php if ($view !== "login" && $view !== "admin/admin"  && $view !== "admin/add_tea") : ?>
        <div class="footer">
            <div class="row" id="info_footer">
                <aside class="col-xl-4 col-lg-4 col-md-12 col-sm-12" id="coordonnees">
                    <section>
                        <h4>Coordonnées</h4>
                        <div>
                            <p>Mauriac<br>
                                26 rue Charles Périé<br>
                                06 12 34 56 78</p>
                            <p></p>
                        </div>
                    </section>
                </aside>

                <aside id="footer-title" class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                    <h4>CHEZ MELLIE</h4>
           
                    <a href="https://www.tripadvisor.fr/Restaurant_Review-g1639465-d17728791-Reviews-Chez_Mellie-Mauriac_Cantal_Auvergne_Rhone_Alpes.html" target="_blank"> <img src="https://img.icons8.com/doodle/48/000000/tripadvisor.png" /> </a>
                    <a href="https://www.facebook.com/chezmellie/" target="_blank"> <img src="https://img.icons8.com/fluent/48/000000/facebook-new.png" /> </a>
                    <a href="https://www.instagram.com/chezmellie/" target="_blank"> <img src="https://img.icons8.com/fluent/48/000000/instagram-new.png" /> </a>
                </aside>
                <aside class="col-xl-4 col-lg-4 col-md-12 col-sm-12" id="contact-footer">
                    <section>
                        <h4>Nous contacter</h4>

                        <a href="<?= buildUrl('/contact'); ?>">
                            <img src="https://img.icons8.com/fluent/48/000000/filled-message.png" />
                        </a>

                    </section>
                </aside>
            </div>

        </div>
    <?php endif ?>
  

    <!-- Footer <script src="js/app.js"></script>-->
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

    <script src="js/news.js"></script>




</body>

</html>