        <!--ONGLET CONTACT -->


        <div class="row" id="infocontact">
          <div id="colonne1" class="col-xl-3 col-lg-3 col-md-12 col-sm-12">


            <img src="https://img.icons8.com/flat_round/64/000000/clock--v1.png" />

            <h3>Horaires</h3>
            <p>Semaine:</p>
            <p>8h - 18h</p>
            <p>Samedi:</p>
            <p>8h -12h</p>
            <p>Dimanche:</p>
            <p>FERME</p>

          </div>

          <div id="centre" class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
            <div id="centre-inner">

              <!-- Contact form -->
              <form action="<?= buildUrl('/contact'); ?>" name="contactForm" method="post" enctype="multipart/form-data">
                <?php echo '<p>' . $message . '</p>' ?>
                <h2>Contact</h2>
                <div class="form-group">


                  <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Votre email...">
                  </div>



                  <div class="form-group">
                    <label>Message</label>
                    <textarea class="form-control" name="message" id="message" rows="4" placeholder="Votre message..."></textarea>
                  </div>

                  <input type="submit" name="send" value="Send" class="btn btn-dark btn-block">
              </form>
            </div>
          </div>
        </div>

        <div id="colonne2" class="col-xl-3 col-lg-3 col-md-12 col-sm-12">
          <img src="https://img.icons8.com/fluent/64/000000/address.png" />
          <h3>Adresse</h3>
          <p>Mauriac<br>
            26 rue Charles Périé<br>
        </div>


        <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d44965.28960875341!2d2.2858526387123397!3d45.22087969918796!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f817603f012829%3A0x4093cafcbeacae0!2s15200%20Mauriac!5e0!3m2!1sfr!2sfr!4v1599050226151!5m2!1sfr!2sfr" width="600" height="550" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        <!-- FIN ONGLET CONTACT-->


        <!-- JavaScript -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.min.js"></script>

        <script>
          $(function() {
            $("form[name='contactForm']").validate({
              // Define validation rules
              rules: {

                email: "required",

                message: "required",

                email: {
                  required: true,
                  email: true
                },

                message: {
                  required: true
                }
              },
              // Specify validation error messages
              messages: {

                email: {
                  required: "Please enter your email",
                  minlength: "Please enter a valid email address"
                },


                message: "Please enter your message"
              },
              submitHandler: function(form) {
                form.submit();
              }
            });
          });
        </script>